# go lang iamge
#FROM golang:1.16.5-buster
FROM golang:1.15.2

#Go Modules使用
ENV GO111MODULE=on
ENV GOPROXY=https://goproxy.io

#ワーキングディレクトリ設定
COPY . /go/src/gin-project/
WORKDIR /go/src/gin-project/

# cosmtrek/airのインストール
RUN go get -u github.com/cosmtrek/air
# delveのインストール
RUN go get -u github.com/go-delve/delve/cmd/dlv
#その他デバッグ・開発用パッケージインストール?
RUN go get -u github.com/uudashr/gopkgs/v2/cmd/gopkgs
RUN go get -u github.com/ramya-rao-a/go-outline
RUN go get -u github.com/cweill/gotests/gotests
RUN go get -u github.com/fatih/gomodifytags
RUN go get -u github.com/josharian/impl
RUN go get -u github.com/haya14busa/goplay/cmd/goplay
RUN go get -u github.com/go-delve/delve/cmd/dlv@master
# Linter
RUN go get -u honnef.co/go/tools/cmd/staticcheck
# Language Server?
RUN go get -u golang.org/x/tools/gopls@latest
# コードフォーマット
RUN go get -u golang.org/x/tools/cmd/goimports


# airの起動
CMD air -c .air.toml

